"""VerifyAIGeneratedImageEngine (VAI) - AI-generated/tampered image detection.

Replaces isgen.ai (external) with local, keyless analysis:
* ``metadata_analysis`` - inspects EXIF/C2PA for AI-generation or tampering signals.
* ``deepscan_fake_image_verification`` / ``isgenAI`` - run a *local* Hugging Face
  image-classifier (``ml`` extra). ``isgenAI`` is kept as an alias to make migration
  from OAtlas mechanical, but it hits the local model, never an external service.
* ``combined_AI_image_verification`` - aggregates the above into one verdict.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict

from openatlas.core.registry import BaseTool, ToolRegistry, ToolResult, ToolSpec
from openatlas.logger import get_logger
from openatlas.tools.image_analysis import StaticImageExtractionEngine

log = get_logger("openatlas.tools.vai")

_DEFAULT_MODEL = os.getenv("OPENATLAS_DEEPFAKE_MODEL", "prithivMLmods/Deep-Fake-Detector-v2-Model")

# Metadata substrings that hint at AI generation.
_AI_HINTS = ["stable diffusion", "midjourney", "dall-e", "dalle", "firefly", "generated by ai",
             "openai", "sdxl", "comfyui", "automatic1111", "gemini", "imagen"]


def _local_classifier(image_path: str) -> Dict[str, Any]:
    try:
        from transformers import pipeline  # type: ignore

        clf = pipeline("image-classification", model=_DEFAULT_MODEL)
        preds = clf(image_path)
        return {"available": True, "model": _DEFAULT_MODEL, "predictions": preds}
    except Exception as exc:
        return {"available": False, "reason": f"local model unavailable ({exc}); "
                                              f"install with `poetry install --with ml`"}


@ToolRegistry.register("verify-ai-generated-image")
class VerifyAIGeneratedImageEngine(BaseTool):
    abbrev = "VAI"
    description = "Detect AI-generated/edited images via C2PA/EXIF + local models (no isgen key)."

    specs = {
        "metadata_analysis": ToolSpec(
            name="metadata_analysis",
            description="Inspect an image's metadata/C2PA for AI-generation or tampering signals.",
            parameters={"image_path": {"type": "string", "required": True, "description": "Image path"}},
            backend="local metadata",
        ),
        "deepscan_fake_image_verification": ToolSpec(
            name="deepscan_fake_image_verification",
            description="Run a local Hugging Face deepfake/AI-image classifier (ml extra).",
            parameters={"image_path": {"type": "string", "required": True, "description": "Image path"}},
            backend="HF transformers (local, ml extra)",
        ),
        "isgenAI": ToolSpec(
            name="isgenAI",
            description="Local replacement for isgen.ai - runs the local classifier (no external key).",
            parameters={"image_path": {"type": "string", "required": True, "description": "Image path"}},
            backend="HF transformers (local, ml extra)",
        ),
        "combined_AI_image_verification": ToolSpec(
            name="combined_AI_image_verification",
            description="Aggregate metadata analysis + local model detection into one verdict.",
            parameters={"image_path": {"type": "string", "required": True, "description": "Image path"}},
            backend="local metadata + HF model",
        ),
    }

    @staticmethod
    def metadata_analysis(image_path: str) -> ToolResult:
        if not Path(image_path).exists():
            return ToolResult.failure("metadata_analysis", f"file not found: {image_path}")
        meta = StaticImageExtractionEngine.extract_metadata(image_path).content
        blob = str(meta).lower()
        hints = [h for h in _AI_HINTS if h in blob]
        has_c2pa = meta.get("c2pa") is not None
        return ToolResult(
            tool_name="metadata_analysis",
            content={"image": image_path, "ai_metadata_hints": hints,
                     "has_c2pa_provenance": has_c2pa, "metadata": meta},
            success=True,
        )

    @staticmethod
    def deepscan_fake_image_verification(image_path: str) -> ToolResult:
        if not Path(image_path).exists():
            return ToolResult.failure("deepscan_fake_image_verification", f"file not found: {image_path}")
        res = _local_classifier(image_path)
        if not res.get("available"):
            return ToolResult.unavailable("deepscan_fake_image_verification", res["reason"])
        return ToolResult(tool_name="deepscan_fake_image_verification", content=res, success=True)

    @staticmethod
    def isgenAI(image_path: str) -> ToolResult:
        res = VerifyAIGeneratedImageEngine.deepscan_fake_image_verification(image_path)
        res.tool_name = "isgenAI"
        res.metadata["note"] = "isgen.ai replaced by a local model; no external service or key"
        return res

    @staticmethod
    def combined_AI_image_verification(image_path: str) -> ToolResult:
        if not Path(image_path).exists():
            return ToolResult.failure("combined_AI_image_verification", f"file not found: {image_path}")
        meta = VerifyAIGeneratedImageEngine.metadata_analysis(image_path)
        model = VerifyAIGeneratedImageEngine.deepscan_fake_image_verification(image_path)
        return ToolResult(
            tool_name="combined_AI_image_verification",
            content={"metadata": meta.content, "model": model.content,
                     "model_available": model.success},
            success=True,
        )
