"""``python -m openatlas.utils.forge`` - scaffolder + verifier used by skill-forge.

Subcommands:
  new-engine   Scaffold a new engine module, register it, add a methods.yaml block,
               and write a pytest stub.
  verify       Run the verification harness for a function (or all functions).

The generated engine follows the project's BaseTool/ToolSpec/ToolResult pattern and is
public-data-only by construction (no auth headers, no keys, robots-gated scraping).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from openatlas.config import Config

ENGINE_TEMPLATE = '''\
"""{engine} ({abbrev}) - {description}

Generated by skill-forge. Free/keyless/local only; public data only.
"""

from __future__ import annotations

from openatlas.core.registry import BaseTool, ToolRegistry, ToolResult, ToolSpec
{maybe_http_import}

@ToolRegistry.register("{common_name}")
class {engine}(BaseTool):
    abbrev = "{abbrev}"
    description = "{description}"

    specs = {{
        "{function}": ToolSpec(
            name="{function}",
            description="{fdesc}",
            parameters={{"target": {{"type": "string", "required": True,
                                    "description": "The target to process"}}}},
            backend="{backend}",
            network={network},
            scrapes_web={scrapes_web},
            needs_llm={needs_llm},
        ),
    }}

    @staticmethod
    def {function}(target: str) -> ToolResult:
        # TODO: implement using free/keyless/local backends only.
        # For public APIs use openatlas.utils.http.api_get_json; for web PAGES use the
        # robots-gated fetch helper (and set scrapes_web=True on the spec above).
        # Return ToolResult.unavailable(...) when the backend is unreachable so the
        # function degrades gracefully instead of crashing.
        return ToolResult(
            tool_name="{function}",
            content={{"target": target, "result": None, "note": "not yet implemented"}},
            success=True,
        )
'''

PYTEST_TEMPLATE = '''\
"""Auto-generated smoke test for {engine}."""

from openatlas.core.registry import ToolResult
from openatlas.tools.{module} import {engine}


def test_{function}_returns_toolresult():
    result = {engine}.{function}(target="example")
    assert isinstance(result, ToolResult)
    assert result.tool_name == "{function}"
    # must be JSON-serialisable
    result.to_json()
'''

METHODS_BLOCK = '''\

{engine}:
  common_name: {common_name}
  abbrev: {abbrev}
  description: {description}
  functions:
    {function}:
      description: {fdesc}
      arguments:
        target: {{type: string, required: true, description: The target to process}}
'''


def _tools_dir() -> Path:
    return Path(Config.files.package_root) / "tools"


def cmd_new_engine(a: argparse.Namespace) -> int:
    module = a.module or _camel_to_snake(a.engine)
    path = _tools_dir() / f"{module}.py"
    if path.exists() and not a.force:
        print(f"refusing to overwrite {path} (use --force)")
        return 1

    maybe_http = ""
    if a.scrapes_web:
        maybe_http = "from openatlas.utils.http import scrape_get\n"
    elif a.network:
        maybe_http = "from openatlas.utils.http import api_get_json\n"

    path.write_text(
        ENGINE_TEMPLATE.format(
            engine=a.engine, abbrev=a.abbrev, common_name=a.common_name,
            description=a.description, function=a.function,
            fdesc=a.function_description or a.description, backend=a.backend,
            network=bool(a.network or a.scrapes_web), scrapes_web=bool(a.scrapes_web),
            needs_llm=bool(a.needs_llm), maybe_http_import=maybe_http,
        ),
        encoding="utf-8",
    )
    print(f"wrote {path}")

    # Register import in tools/__init__.py
    init = _tools_dir() / "__init__.py"
    text = init.read_text(encoding="utf-8")
    if module not in text:
        text += f"\nfrom openatlas.tools import {module}  # noqa: F401,E402  (skill-forge)\n"
        init.write_text(text, encoding="utf-8")
        print(f"registered import in {init}")

    # Append methods.yaml block
    my = Path(Config.files.methods_yaml)
    my.write_text(
        my.read_text(encoding="utf-8") + METHODS_BLOCK.format(
            engine=a.engine, common_name=a.common_name, abbrev=a.abbrev,
            description=a.description, function=a.function,
            fdesc=a.function_description or a.description,
        ),
        encoding="utf-8",
    )
    print(f"documented in {my}")

    # Write pytest
    test = Path(Config.files.project_root) / "tests" / f"test_{module}.py"
    test.write_text(
        PYTEST_TEMPLATE.format(engine=a.engine, module=module, function=a.function),
        encoding="utf-8",
    )
    print(f"wrote {test}")
    print("\nNext: run `python -m openatlas.utils.forge verify %s`" % a.function)
    return 0


def cmd_verify(a: argparse.Namespace) -> int:
    from openatlas.utils.smoke_run import verify_all, verify_function

    if a.function:
        report = verify_function(a.function)
        ok = report["ok"]
    else:
        report = verify_all()
        ok = report["ok"]
    print(json.dumps(report, indent=2))
    return 0 if ok else 1


def _camel_to_snake(name: str) -> str:
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i:
            out.append("_")
        out.append(ch.lower())
    return "".join(out).replace("_engine", "")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="openatlas.utils.forge",
                                description="Scaffold and verify OpenAtlas engines.")
    sub = p.add_subparsers(dest="cmd", required=True)

    ne = sub.add_parser("new-engine", help="scaffold a new engine")
    ne.add_argument("--engine", required=True, help="EngineClass name (CamelCase)")
    ne.add_argument("--common-name", required=True, help="registry common-name (kebab-case)")
    ne.add_argument("--abbrev", required=True, help="short abbreviation")
    ne.add_argument("--function", required=True, help="function name (snake_case)")
    ne.add_argument("--description", default="new OSINT engine")
    ne.add_argument("--function-description", default="")
    ne.add_argument("--backend", default="local")
    ne.add_argument("--module", default="", help="module filename (default derived)")
    ne.add_argument("--network", action="store_true")
    ne.add_argument("--scrapes-web", action="store_true")
    ne.add_argument("--needs-llm", action="store_true")
    ne.add_argument("--force", action="store_true")
    ne.set_defaults(func=cmd_new_engine)

    v = sub.add_parser("verify", help="verify a function (or all)")
    v.add_argument("function", nargs="?", default="")
    v.set_defaults(func=cmd_verify)
    return p


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
